name: Cartographer2
main: io.github.bananapuncher714.cartographer.core.Cartographer
version: 14
description: Adds a serverside minimap to Minecraft
author: BananaPuncher714
api-version: 1.13
softdepend:
- "Multiverse-Core"