## VanillaPlus config

# Blacklisted worlds. Used as a whitelist if blacklist is false
blacklist: true
blacklisted-worlds: []

# Find the cursor types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/map/MapCursor.Type.html
# Not every icon may be available in your version
#
# Visibility options are FULL, PARTIAL, and NONE
#
# Cursors for basic icons
cursors:
  spawn:
    enabled: true
    icon: MANSION WHITE_CIRCLE
    default-visibility: FULL
    show-name: true
    display-name: "Spawn"
  death:
    enabled: true
    icon: RED_X WHITE_CROSS
    default-visibility: FULL
    show-name: true
    display-name: "§cDeath"
    # The minimum range that is required for the death point to be visible
    # For example, a min range of 100 means that the player can only see if on the map if they're 100 or more blocks away
    min-range: 0

# Options for displaying other players
players:
  enabled: true
  icon: PLAYER WHITE_POINTER
  range: 512
  default-visibility: PARTIAL
  show-name: true

# Options for displaying entities
# Find a list of all the entitytypes here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# Required permissions are vanillaplus.cursor.entity.<entitytype>
# Use "MATERIAL:DURABILITY" format for the items, if durability is required.
entity:
  BLAZE:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  CREEPER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  DROWNED:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ELDER_GUARDIAN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ENDERMITE:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  EVOKER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  GHAST:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  GUARDIAN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  HOGLIN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  HUSK:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  MAGMA_CUBE:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PHANTOM:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PIGLIN_BRUTE:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PILLAGER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  RAVAGER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SHULKER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SILVERFISH:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SKELETON:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SLIME:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  STRAY:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  VEX:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  VINDICATOR:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  WITCH:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  WITHER_SKELETON:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ZOGLIN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ZOMBIE:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ZOMBIE_VILLAGER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  CAVE_SPIDER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ENDERMAN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PIGLIN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SPIDER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ZOMBIFIED_PIGLIN:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  GIANT:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  ILLUSIONER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR

  ENDER_DRAGON:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  WITHER:
    icon: RED_MARKER RED_POINTER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR

  VILLAGER:
    icon: BLUE_MARKER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  WANDERING_TRADER:
    icon: BLUE_MARKER BLUE_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR

  BAT:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  CAT:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  CHICKEN:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  COD:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  COW:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  DONKEY:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  FOX:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  HORSE:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  MUSHROOM_COW:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  MULE:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  OCELOT:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PARROT:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PIG:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  POLAR_BEAR:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  RABBIT:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SALMON:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SHEEP:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SKELETON_HORSE:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SNOWMAN:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  SQUID:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  STRIDER:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  TROPICAL_FISH:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  TURTLE:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  BEE:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  DOLPHIN:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  IRON_GOLEM:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  LLAMA:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PANDA:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  PUFFERFISH:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR
  WOLF:
    icon: FRAME GREEN_POINTER
    range: 64
    default-visibility: PARTIAL
    show-name: true
    item: AIR